name = "klubok_gleam"
version = "0.1.0"
description = "Do notation pipes for functions which easy to mock"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "klubok-gleam" }
gleam = ">= 1.4.0"

[javascript.deno]
allow_read = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
